/* eslint-disable no-console */
import type { PackageUpdate } from '../src/types'
import { describe, expect, it } from 'bun:test'
import { updateDependencyFile } from '../src/utils/dependency-file-parser'

describe('Regression Test - Dependency Constraint Preservation', () => {
  describe('zip/unzip cross-contamination bug', () => {
    it('should preserve correct constraints for zip and unzip packages', async () => {
      // This is the exact content from the stacks deps.yaml file
      const content = `# Please note, this file is auto-generated based on your ./config & local environment.
# It's recommended to keep it in your project's root directory, and to commit it.
#
# The framework understands your project's dependencies, knows which ones are
# already installed in your environment, and which aren't — prompting
# to automatically install missing dependencies when needed.
#
# To learn more, please visit:
# https://stacksjs.org/docs/dependency-management

dependencies:
  aws/cli: ^2.22.26
  bun: ^1.2.13
  gh: ^2.69.0
  zip: ^3.0
  unzip: ^6.0
  sqlite3: ^3.47.2
  node: ^22.12.0 # only temporarily needed until bun & vue-tsc issue is resolved
  # mailpit: ^1.21.8
  # redis: ^7.4.1
  # rust: ^1.74.1
  # openjdk.org: ^21.0.3.6`

      // These are the actual updates that would be generated by dependency resolution
      const updates: PackageUpdate[] = [
        {
          name: 'zip',
          currentVersion: '^3.0',
          newVersion: '3.0.0',
          updateType: 'patch',
          dependencyType: 'dependencies',
          file: 'deps.yaml',
          metadata: undefined,
        },
        {
          name: 'unzip',
          currentVersion: '^6.0',
          newVersion: '6.0.0',
          updateType: 'patch',
          dependencyType: 'dependencies',
          file: 'deps.yaml',
          metadata: undefined,
        },
      ]

      const result = await updateDependencyFile('deps.yaml', content, updates)

      // CRITICAL: These are the exact assertions that must pass to prevent regression
      expect(result).toContain('zip: ^3.0.0') // zip should be updated to ^3.0.0
      expect(result).toContain('unzip: ^6.0.0') // unzip should be updated to ^6.0.0 (NOT ^3.0.0!)

      // Ensure no cross-contamination happened
      expect(result).not.toContain('unzip: ^3.0.0') // This was the bug - unzip getting zip's version
      expect(result).not.toMatch(/^\s*zip: \^6\.0\.0/m) // zip should not get unzip's version

      // Verify other packages remain unchanged
      expect(result).toContain('aws/cli: ^2.22.26')
      expect(result).toContain('bun: ^1.2.13')
      expect(result).toContain('gh: ^2.69.0')
      expect(result).toContain('sqlite3: ^3.47.2')
      expect(result).toContain('node: ^22.12.0')
    })

    it('should handle mixed updates in real-world scenario', async () => {
      const content = `dependencies:
  aws/cli: ^2.22.26
  bun: ^1.2.19
  gh: ^2.76.1
  zip: ^3.0
  unzip: ^6.0
  sqlite3: ^3.50.3
  node: ^22.17.1`

      // Simulate what happens when multiple packages get updated at once
      const updates: PackageUpdate[] = [
        {
          name: 'aws/cli',
          currentVersion: '^2.22.26',
          newVersion: '2.27.60',
          updateType: 'minor',
          dependencyType: 'dependencies',
          file: 'deps.yaml',
          metadata: undefined,
        },
        {
          name: 'bun',
          currentVersion: '^1.2.19',
          newVersion: '1.2.19',
          updateType: 'patch',
          dependencyType: 'dependencies',
          file: 'deps.yaml',
          metadata: undefined,
        },
        {
          name: 'zip',
          currentVersion: '^3.0',
          newVersion: '3.0.0',
          updateType: 'patch',
          dependencyType: 'dependencies',
          file: 'deps.yaml',
          metadata: undefined,
        },
        {
          name: 'unzip',
          currentVersion: '^6.0',
          newVersion: '6.0.0',
          updateType: 'patch',
          dependencyType: 'dependencies',
          file: 'deps.yaml',
          metadata: undefined,
        },
      ]

      const result = await updateDependencyFile('deps.yaml', content, updates)

      // This reproduces the exact scenario from the user's reported issue
      expect(result).toContain('aws/cli: ^2.27.60')
      expect(result).toContain('bun: ^1.2.19')
      expect(result).toContain('zip: ^3.0.0')
      expect(result).toContain('unzip: ^6.0.0') // MUST be ^6.0.0, not ^3.0.0!

      // Log the result for debugging if the test fails
      if (result.includes('unzip: ^3.0.0')) {
        console.log('REGRESSION: unzip got wrong version!')
        console.log('Full result:')
        console.log(result)
      }
    })
  })

  describe('similar package name edge cases', () => {
    it('should handle packages that are substrings of each other', async () => {
      const content = `dependencies:
  react: ^18.0.0
  react-dom: ^18.0.0
  react-router: ^6.0.0
  react-router-dom: ^6.0.0`

      const updates: PackageUpdate[] = [
        {
          name: 'react',
          currentVersion: '^18.0.0',
          newVersion: '18.2.0',
          updateType: 'minor',
          dependencyType: 'dependencies',
          file: 'deps.yaml',
          metadata: undefined,
        },
      ]

      const result = await updateDependencyFile('deps.yaml', content, updates)

      expect(result).toContain('react: ^18.2.0')
      expect(result).toContain('react-dom: ^18.0.0')
      expect(result).toContain('react-router: ^6.0.0')
      expect(result).toContain('react-router-dom: ^6.0.0')
    })

    it('should handle packages with special characters in YAML format', async () => {
      const content = `dependencies:
  "@types/node": ^20.0.0
  "@types/node-fetch": ^2.0.0
  node: ^20.0.0`

      const updates: PackageUpdate[] = [
        {
          name: 'node',
          currentVersion: '^20.0.0',
          newVersion: '20.5.0',
          updateType: 'minor',
          dependencyType: 'dependencies',
          file: 'deps.yaml',
          metadata: undefined,
        },
      ]

      const result = await updateDependencyFile('deps.yaml', content, updates)

      // Should only update unquoted 'node', not '@types/node' or '@types/node-fetch'
      expect(result).toContain('node: ^20.5.0')
      expect(result).toContain('"@types/node": ^20.0.0')
      expect(result).toContain('"@types/node-fetch": ^2.0.0')
    })
  })

  describe('comment and multi-occurrence corruption (stacksjs/buddy#1453)', () => {
    const mk = (name: string, currentVersion: string, newVersion: string): PackageUpdate => ({
      name,
      currentVersion,
      newVersion,
      updateType: 'minor',
      dependencyType: 'dependencies',
      file: 'deps.yaml',
      metadata: undefined,
    })

    it('should not take its replacement text from a package name inside a comment', async () => {
      // Verbatim from the PR that produced a deps.yaml which no longer parsed:
      // the comment mentions `sqlite: latest`, and because the old regex was
      // unanchored that prose was the FIRST match, so its captures drove the
      // replacement for the real key - and its greedy leading `\s*` swallowed
      // the newline, collapsing `sqlite` onto the `postgres` line.
      const content = `# That is not hypothetical: \`sqlite: latest\` was fine only because the SDK did
# not support sqlite.org and skipped it with a warning.
dependencies:
  bun: ^1.3.14
  mysql: ^8.0.45
  postgres: ^18.0.0
  sqlite: ^3.52.0
`

      const result = await updateDependencyFile('deps.yaml', content, [
        mk('postgres', '^18.0.0', '18.6'),
        mk('sqlite', '^3.52.0', '3.53.4'),
      ])

      // The whole point: the file still parses.
      expect(() => Bun.YAML.parse(result)).not.toThrow()

      // Both keys survive, on their own lines, with their own versions.
      expect(result).toMatch(/^ {2}postgres: \^18\.6$/m)
      expect(result).toMatch(/^ {2}sqlite: \^3\.53\.4$/m)

      // The comment is prose and must come out byte-identical.
      expect(result).toContain('# That is not hypothetical: `sqlite: latest` was fine only because the SDK did')
    })

    it('should rewrite each occurrence from its own captures, not the first match', async () => {
      // A `g` regex was used with a single replacement string built from the
      // first match, so the first occurrence's rendered text was written over
      // every other occurrence. Two occurrences with DIFFERENT prefixes are
      // what exposes it: with the same prefix the wrong answer and the right
      // answer are identical.
      const content = `dependencies:
  typescript: ^5.0.0

devDependencies:
  typescript: ~4.9.0
`

      const result = await updateDependencyFile('deps.yaml', content, [
        mk('typescript', '^5.0.0', '5.6.2'),
      ])

      expect(() => Bun.YAML.parse(result)).not.toThrow()
      // Each line keeps the prefix it was written with.
      expect(result).toMatch(/^ {2}typescript: \^5\.6\.2$/m)
      expect(result).toMatch(/^ {2}typescript: ~5\.6\.2$/m)
    })

    it('should leave a commented-out dependency alone', async () => {
      const content = `dependencies:
  # redis: ^7.4.1 # disabled for now
  sqlite3: ^3.50.3
`

      const result = await updateDependencyFile('deps.yaml', content, [
        mk('redis', '^7.4.1', '7.5.0'),
      ])

      expect(result).toContain('# redis: ^7.4.1 # disabled for now')
      expect(result).not.toContain('7.5.0')
    })

    it('should respect a dynamic version even when it is quoted', async () => {
      // `"*"` captured with its quotes missed the `['latest', '*', ...]` test,
      // so the guard never fired and the prefix logic produced `"*"3.13.5`.
      const content = `dependencies:
  python.org: "*"
  node: "latest"
`

      const result = await updateDependencyFile('deps.yaml', content, [
        mk('python.org', '*', '3.13.5'),
        mk('node', 'latest', '22.17.1'),
      ])

      expect(() => Bun.YAML.parse(result)).not.toThrow()
      expect(result).toContain('python.org: "*"')
      expect(result).toContain('node: "latest"')
      expect(result).not.toContain('3.13.5')
      expect(result).not.toContain('22.17.1')
    })

    it('should preserve the quoting style of a version it does update', async () => {
      const content = `dependencies:
  typescript: "^5.0.0"
  node: '^22.12.0'
`

      const result = await updateDependencyFile('deps.yaml', content, [
        mk('typescript', '^5.0.0', '5.6.2'),
        mk('node', '^22.12.0', '22.17.1'),
      ])

      expect(() => Bun.YAML.parse(result)).not.toThrow()
      expect(result).toContain('typescript: "^5.6.2"')
      expect(result).toContain('node: \'^22.17.1\'')
    })

    it('should still update a file that did not parse as YAML to begin with', async () => {
      // The parse guard exists to stop THIS function corrupting a file. A file
      // that was already broken is not its business, and bailing there would
      // silently stop updating it.
      const content = `dependencies:
  bun: ^1.3.14
   : this line is not valid yaml
`

      expect(() => Bun.YAML.parse(content)).toThrow()

      const result = await updateDependencyFile('deps.yaml', content, [
        mk('bun', '^1.3.14', '1.4.2'),
      ])

      expect(result).toContain('bun: ^1.4.2')
    })
  })

  describe('YAML comment preservation', () => {
    it('should preserve inline comments when updating dependencies', async () => {
      const content = `dependencies:
  aws/cli: ^2.22.26
  bun: ^1.2.19
  gh: ^2.76.1
  zip: ^3.0
  unzip: ^6.0
  sqlite3: ^3.50.3
  node: ^22.12.0 # only temporarily needed until bun & vue-tsc issue is resolved`

      const updates: PackageUpdate[] = [
        {
          name: 'node',
          currentVersion: '^22.12.0',
          newVersion: '22.17.1',
          updateType: 'minor',
          dependencyType: 'dependencies',
          file: 'deps.yaml',
          metadata: undefined,
        },
      ]

      const result = await updateDependencyFile('deps.yaml', content, updates)

      // Should update the version but preserve the comment
      expect(result).toContain('node: ^22.17.1 # only temporarily needed until bun & vue-tsc issue is resolved')
      expect(result).not.toContain('node: ^22.12.0') // Old version should be gone
      expect(result).not.toContain('node: ^22.17.1\n') // Should not strip the comment
    })

    it('should preserve comments for multiple dependencies with comments', async () => {
      const content = `dependencies:
  aws/cli: ^2.22.26 # AWS command line interface
  bun: ^1.2.19 # JavaScript runtime
  node: ^22.12.0 # only temporarily needed until bun & vue-tsc issue is resolved
  # redis: ^7.4.1 # disabled for now
  sqlite3: ^3.50.3 # database engine`

      const updates: PackageUpdate[] = [
        {
          name: 'aws/cli',
          currentVersion: '^2.22.26',
          newVersion: '2.27.60',
          updateType: 'minor',
          dependencyType: 'dependencies',
          file: 'deps.yaml',
          metadata: undefined,
        },
        {
          name: 'node',
          currentVersion: '^22.12.0',
          newVersion: '22.17.1',
          updateType: 'minor',
          dependencyType: 'dependencies',
          file: 'deps.yaml',
          metadata: undefined,
        },
      ]

      const result = await updateDependencyFile('deps.yaml', content, updates)

      // Should update versions but preserve all comments
      expect(result).toContain('aws/cli: ^2.27.60 # AWS command line interface')
      expect(result).toContain('bun: ^1.2.19 # JavaScript runtime')
      expect(result).toContain('node: ^22.17.1 # only temporarily needed until bun & vue-tsc issue is resolved')
      expect(result).toContain('# redis: ^7.4.1 # disabled for now') // Full-line comments should remain
      expect(result).toContain('sqlite3: ^3.50.3 # database engine')
    })

    it('should handle dependencies without comments alongside ones with comments', async () => {
      const content = `dependencies:
  zip: ^3.0
  unzip: ^6.0 # extraction utility
  sqlite3: ^3.50.3`

      const updates: PackageUpdate[] = [
        {
          name: 'zip',
          currentVersion: '^3.0',
          newVersion: '3.0.0',
          updateType: 'patch',
          dependencyType: 'dependencies',
          file: 'deps.yaml',
          metadata: undefined,
        },
        {
          name: 'unzip',
          currentVersion: '^6.0',
          newVersion: '6.0.0',
          updateType: 'patch',
          dependencyType: 'dependencies',
          file: 'deps.yaml',
          metadata: undefined,
        },
      ]

      const result = await updateDependencyFile('deps.yaml', content, updates)

      // Should update both, preserving comment only where it exists
      expect(result).toContain('zip: ^3.0.0')
      expect(result).toContain('unzip: ^6.0.0 # extraction utility')
      expect(result).toContain('sqlite3: ^3.50.3')
    })
  })
})
